const usersDatabase = [
	{
		id: "1",
		name: "John Doe",
		email: "johndoe@example.com",
		password: "password123",
		entries: 0,
		colors: ["#ff0000", "#00ff00", "#0000ff"],
		joined: new Date(),
	},
	{
		id: "2",
		name: "Jane Smith",
		email: "janesmith@example.com",
		password: "password456",
		entries: 3,
		colors: ["#ffff00", "#ff00ff", "#00ffff"],
		joined: new Date(),
	},
	{
		id: "3",
		name: "Bob Johnson",
		email: "bobjohnson@example.com",
		password: "password789",
		entries: 5,
		colors: ["#000000", "#ffffff", "#808080"],
		joined: new Date(),
	},
	{
		id: "4",
		name: "Sarah Lee",
		email: "sarahlee@example.com",
		password: "password101",
		entries: 1,
		colors: ["#00ff00", "#00ffff", "#ff00ff"],
		joined: new Date(),
	},
	{
		id: "5",
		name: "Michael Chen",
		email: "michaelchen@example.com",
		password: "password202",
		entries: 10,
		colors: ["#ff0000", "#0000ff", "#ffff00"],
		joined: new Date(),
	},
	{
		id: "6",
		name: "Emily Davis",
		email: "emilydavis@example.com",
		password: "password303",
		entries: 2,
		colors: ["#ff00ff", "#00ffff", "#ffffff"],
		joined: new Date(),
	},
	{
		id: "7",
		name: "William Jackson",
		email: "williamjackson@example.com",
		password: "password404",
		entries: 7,
		colors: ["#808080", "#000000", "#ff00ff"],
		joined: new Date(),
	},
	{
		id: "8",
		name: "Samantha Lee",
		email: "samanthalee@example.com",
		password: "password505",
		entries: 4,
		colors: ["#00ffff", "#0000ff", "#ff0000"],
		joined: new Date(),
	},
	{
		id: "9",
		name: "Thomas Baker",
		email: "thomasbaker@example.com",
		password: "password606",
		entries: 6,
		colors: ["#ffffff", "#000000", "#ff0000"],
		joined: new Date(),
	},
	{
		id: "10",
		name: "Ella Kim",
		email: "ellakim@example.com",
		password: "password707",
		entries: 8,
		colors: ["#ffff00", "#00ff00", "#00ffff"],
		joined: new Date(),
	},
];

export default usersDatabase;
